### ISSUE TITLE
Detect WebRTC activity

### ISSUE THREAD

**Issue by leplatrem** [autonome/Dormancy#10]
Dormancy suspends tabs running WebRTC (e.g. conversation in https://appear.in)

**Comment by autonome** [comment]
Hi! Thanks for filing this.

It will be tough to get this correct.

Sometimes that type of content in the background is exactly why people use Dormancy. It's battery death to leave it running.

However, there are valid use-cases for this also. For example, being on a call but doing stuff in other tabs while leaving the call in the background.

A mitigation would be to pin the tabs with your active calls. But that's not great either.

I'm not seeing a way to get this "just right". Let me know if you have ideas.

**Comment by leplatrem** [comment]
Thanks for your very detailed feedback.

I think the easiest way would be to use some domain whitelist (#7). Just put `appear.in`  in the whitelist and that's it :) 

I'll close the issue...
