### ISSUE TITLE
Option to keep pinned tabs active (exclude them)

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#13]
As per user report:
> wish there was an option to keep pinned tabs

by erman

**Comment by autonome** [comment]
The addon does not put pinned tabs to sleep... intentionally.

If it does, then there's a new bug since the last fix for that.

I'm not seeing that happen on Firefox Nightly on Mac.

If you can reproduce the problem, can you send your system information and
Firefox version?

**Comment by rugk** [comment]
No, just judged from the evaluation…
