### ISSUE TITLE
Show option in about:addons and not as new icon

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#14]
**Currently:** A toolbar button for setting the timeout.
**I expect:** The same as a simple option in the about:addons

**Why?**
* Because I have more than enough icons from add-ons.
* This is an option, which applies for all tabs/sites, AFAIK.
* I do not need to reset this very frequently (actually, not at all, I just set it when configuring the extension the first time, maybe I do not touch it at all, as I don't care about the exact timing.)

**Comment by autonome** [comment]
I just shipped about:addons support for configuration in version 3.1.0.

I didn't remove the toolbar icon, because that's too easy to do yourself: right-click and choose "Remove from Toolbar".

Thanks for bringing this up!
