### ISSUE TITLE
Keep active window alive may affect tab retirement

### ISSUE THREAD

**Issue by CODE-REaD** [autonome/Dormancy#17]
With Dormancy 3.3.0 running under 58.0.2 (64-bit)/Windows 7 Pro/64, it seems that when I activate the "Keep active window alive" option, tab retirement is either disabled generally or works differently.  Evidence is that when this option is active, tabs which should have been timed out and retired do not need refreshing.

**Comment by autonome** [comment]
Thanks for reporting! Are you still seeing the problem?

**Comment by autonome** [comment]
Reopen if you're still seeing!
