### ISSUE TITLE
Greatest memory savings occur after I stop and restart Firefox

### ISSUE THREAD

**Issue by CODE-REaD** [autonome/Dormancy#18]
With Dormancy 3.3.0 running under 58.0.2 (64-bit)/Windows 7 Pro/64, Dormancy reduces Firefox memory usage significantly.  But if I shut down Firefox and restart it, with Firefox's "Show your windows and tabs from last time" option enabled, tabs retired by Dormancy appear to use markedly less memory and their favicons are not displayed.  I don't remember Firefox behaving this way before I used Dormancy; haven't tested this thoroughly, can validate if needed.

**Comment by autonome** [comment]
Definitely a Firefox thing. There were some bugs in how tabs were loaded/unloaded when they first added the WebExtensions API that Dormancy uses. But Dormancy ultimately has no control over how it is done :(

If you're still seeing this, should file a Firefox bug.
