### ISSUE TITLE
URL lost for some but not all discarded tabs after extended dormancy

### ISSUE THREAD

**Issue by CODE-REaD** [autonome/Dormancy#19]
(FireFox 58.0.2 (64-bit); Dormancy 3.3.0): Dormancy has been "losing" tab content for SOME but not ALL tabs I haven't visited for longer periods (~1 day or more). When this happens, first the tab's title remains but its URL is missing (so the tab can't be reloaded), and eventually its title reverts to "New Tab."

A site this has occurred with: https://sympli.io/blog/2016/12/13/is-the-hamburger-menu-healthy-for-ux/

A site this (so far) has not occurred with, over a nearly equal dormancy period: https://speckyboy.com/analyzing-effectiveness-hamburger-menus-web-design/

**Comment by autonome** [comment]
This is likely an underlying bug in Firefox's tab load/unload/reload code. All Dormancy does is ask nicely for Firefox to do things.

If you're still seeing the problem, comment and reopen! Thanks!
