### ISSUE TITLE
Do not unload - but suspend CPU activity

### ISSUE THREAD

**Issue by ole-tange** [autonome/Dormancy#28]
Dormancy does what it says on the box.

But to me the time to reload the page is problematic, and some state is lost. E.g. how much of a Youtube video you have watched - it starts from the beginning.

I would prefer an option that would not completely unload the tab, but simply to suspend the CPU activity to a tab, and then let the virtual memory system swap out the untouched memory. Preferably with a simple way of whitelisting a tab; maybe by clicking a icon next to the location bar?

Is it possible to extend Dormancy to do this? Or is this a huge change?

**Comment by ole-tange** [comment]
Maybe this can inspire: https://github.com/S-NA/Suspend-background-tabs/blob/master/modules/main.js

```
  let utils = browser.contentWindow.QueryInterface(Components.interfaces.nsIInterfaceRequestor)
                     .getInterface(Components.interfaces.nsIDOMWindowUtils);
  if (suspend)
  {
    utils.suppressEventHandling(true);
    utils.suspendTimeouts();
    browser.__sbtSuspended = true;
}
```

It is unclear to me if that will work in Firefox Quantum.

**Comment by autonome** [comment]
I'd love have this level of granularity, but we only have what the WebExtensions API gives us.

Eventually we'll have this in browsers: https://github.com/WICG/page-lifecycle

**Comment by autonome** [comment]
Closing for now - sadly, there's no ability to do this in the near future.
