### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#31]
@autonome Do you still maintain this extension? Just as there are many open, unmerged/uncommented PRs…

I would otherwise be willing to maintain it/or a fork, if no one replies here… :neutral_face:

**Comment by autonome** [comment]
Yep, still maintained, just not much time. Will try and get some in this
week!

**Comment by sergeevabc** [comment]
How do I visually know if extension is even working, by the way?
There is the following line in my ```userChrome.css```, which makes titles of unloaded tabs less visible. 
```tabbrowser-tab[pending] { opacity: 0.5 !important;}```
But after timeout is passed, titles of tabs expected to be unloaded are still rendered with ```opacity: 1```

**Comment by rugk** [comment]
Usually you do see it when you click on an unloaded tab. Compared to "not-unloaded" tabs they do load a few seconds.

**Comment by autonome** [comment]
Agghgh, I maybe broke everything in the latest update 😭 looking now...
