### ISSUE TITLE
No change in memory use after installing

### ISSUE THREAD

**Issue by Zarani** [autonome/Dormancy#4]
Hi there,

This would be an awesome extension and I installed it hoping that my idling tabs would be unloaded from memory after some minutes (as is in the description of this extension).
But now, after hours of using it the memory used reported both in Windows Task Manager and by the Memory Restart 1.11 add-on still grows like before installing Dormancy, to the same levels.
To be noted that I am using both Tab Group Manager 2011.11.28.1x (FF20 fix1) and Vertical Tabs 0.9.3. Maybe they have relevance in this issue as well as causing another issue with tab titles since I installed Dormancy: that is, for he tabs which would be unloaded by Dormancy the titles change to the following pattern instead of the real page/tab title: "data:text/html,...(last few chars of the page title&lt;/title&gt;" (se also attached screen shot snippet). When clicking on the tab, though, the names restore to their normal visibility. The problem with the tab titles now is just that it is impossible to visually identify the tabs to open, causing me to click on more tabs than required, causing more memory use than required.

What is your opinion on these issues?

Thank you.
![dormancy](https://f.cloud.github.com/assets/1352690/743690/5d666724-e3ed-11e2-8ee3-29197ec12686.png)

**Comment by autonome** [comment]
Ported to WebExtensions API, complete rewrite, so closing this.
