### ISSUE TITLE
Is form data lost when tabs are restored?

### ISSUE THREAD

**Issue by rugk** [autonome/Dormancy#5]
I think that is a very important question and you should clarify that in your Readme/on AMO.

**Comment by autonome** [comment]
Thank you for filing this issue!

The extension should not lose form data.

The extension uses an API in Firefox that does the save/restore action on the tab, and does not itself touch the web page at all.

If form data is lost, then you should file a bug for Firefox: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

I will add a note to the README.md and AMO listing.

**Comment by autonome** [comment]
Updated in both places to provide this information.

**Comment by rugk** [comment]
Nice!
