### ISSUE TITLE
Option to configure tab timeout

### ISSUE THREAD

**Issue by tcitworld** [autonome/Dormancy#9]
I find 5 minutes a little short for my tabs to sleep, so I would like an option page to set the number of minutes.

**Comment by autonome** [comment]
Thanks for filing. This is #1 on my list for Dormancy. Coming soon.

**Comment by autonome** [comment]
Added a toolbar button with UI for configuring a timeout different than the timeout. Just got approved on AMO, so try it out and let me know if you have any problems!
